# Generated by Django 4.0 on 2021-12-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250,verbose_name='Название')),
                ('slug', models.SlugField(max_length=250,verbose_name='Ссылка')),
                ('author', models.CharField(max_length=250,verbose_name='Автор')),
                ('body', models.TextField(verbose_name='Текст')),
                ('categorys', models.CharField(choices=[('album', 'Альбомы'), ('single', 'Новинки песен'), ('videoclip', 'Обзор на видеоклип'), ('group', 'Группы'), ('article', 'Статьи')], default='', max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Познее'), ('published', 'Опубликован')], default='draft', max_length=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
